// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi524M_0ULZEu4vPUfloLUz-r18aIgKr8',
    appId: '1:1064596700126:web:ca18a431858d568e3e3b4f',
    messagingSenderId: '1064596700126',
    projectId: 'thigk-d2c24',
    authDomain: 'thigk-d2c24.firebaseapp.com',
    storageBucket: 'thigk-d2c24.appspot.com',
    measurementId: 'G-X263RT6FDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGkJiGYtwBcdxE6qUA-La-hkD8ajKUOs',
    appId: '1:1064596700126:android:97a2825ccd5d7e693e3b4f',
    messagingSenderId: '1064596700126',
    projectId: 'thigk-d2c24',
    storageBucket: 'thigk-d2c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1ag4TtBZ_z1PF6cofkLuzbNn8LPGM78',
    appId: '1:1064596700126:ios:3bb2f49eebf3477f3e3b4f',
    messagingSenderId: '1064596700126',
    projectId: 'thigk-d2c24',
    storageBucket: 'thigk-d2c24.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1ag4TtBZ_z1PF6cofkLuzbNn8LPGM78',
    appId: '1:1064596700126:ios:3bb2f49eebf3477f3e3b4f',
    messagingSenderId: '1064596700126',
    projectId: 'thigk-d2c24',
    storageBucket: 'thigk-d2c24.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi524M_0ULZEu4vPUfloLUz-r18aIgKr8',
    appId: '1:1064596700126:web:e40324fbb571e5893e3b4f',
    messagingSenderId: '1064596700126',
    projectId: 'thigk-d2c24',
    authDomain: 'thigk-d2c24.firebaseapp.com',
    storageBucket: 'thigk-d2c24.appspot.com',
    measurementId: 'G-9B5V27MLZG',
  );
}
